name: Test Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  APP_NAME: "ClipBoard Pro"
  APP_ID: "com.clipboardpro.app"

jobs:
  test-linux:
    name: Test Linux Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: Test build
        run: |
          fyne-cross linux \
            -arch amd64 \
            -app-id ${{ env.APP_ID }} \
            -app-build ${{ github.run_number }}

#  test-windows:
#    name: Test Windows Build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Go
#        uses: actions/setup-go@v4
#        with:
#          go-version: "1.23"
#
#      - name: Install fyne-cross
#        run: go install github.com/fyne-io/fyne-cross@latest
#
#      - name: Test build
#        run: |
#          fyne-cross windows \
#            -arch amd64 \
#            -app-id ${{ env.APP_ID }} \
#            -app-build ${{ github.run_number }}
#
#  test-macos:
#    name: Test macOS Build
#    runs-on: macos-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Go
#        uses: actions/setup-go@v4
#        with:
#          go-version: "1.23"
#
#      - name: Install fyne command
#        run: go install fyne.io/tools/cmd/fyne@latest
#
#      - name: Test build
#        run: fyne package -os darwin -release
